avatar:
  type: string
  default: ""
title:
  type: string
  default: "Biskit"
username:
  type: string
  default: "biskit"
bio:
  type: string
  default: "ğŸ‘‹ğŸ½ Welcome to my page! I woooofe Discourse ğŸ‰"
badges:
  type: list
  default: "user;#A461EF;Lounge Lizard;/c/4|certificate;#E45735;Most Trusted;/c/3|heart;#808281;Site Addict;/c/2"
  description:
    en: "Add three custom badges. Properties should be spearated by semicolon in this order: Icon; Icon color; Badge title; Link"
more_badges_title:
  type: string
  default: "+ About"
  description:
    en: "Title of the 'more badges' button"
more_badges_link:
  type: string
  default: "/about"
  description:
    en: "href link of the 'more badges' button"
svg_icons:
  type: "list"
  list_type: "compact"
  default: ""
  description:
    en: "Add FontAwesome 5 icon classes for non-default icons."
animate_card:
  type: bool
  default: true
