avatar:
  type: string
  default: ""
title:
  type: string
  default: "Biskit"
username:
  type: string
  default: "biskit"
bio:
  type: string
  default: "ğŸ‘‹ğŸ½ Welcome to my page! I woooofe Discourse ğŸ‰"
badges:
  type: list
  default: "user;#A461EF;Lounge Lizard;/c/4|certificate;#E45735;Most Trusted;/c/3|heart;#808281;Site Addict;/c/2"
  description: "Add badges"
svg_icons:
  type: "list"
  list_type: "compact"
  default: ""
  description:
    en: "Include FontAwesome 5 icon classes for additional icons."
animate_card:
  type: bool
  default: true

